apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: janus-idp
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.2-1
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 2Gi
      resources:
        limits:
          cpu: 300m
        requests:
          cpu: 200m
      sidecars:
        replicaCertCopy:
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      global:
        # Save backups for 7 days, this means 1 full backups with 6 differential ones in between
        repo1-retention-full: "1"
        repo1-retention-full-type: count
      repoHost:
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 200m
      repos:
        - name: repo1
          schedules:
            # Every sunday at 01:00 full backup
            full: "0 1 * * 0"
            # Monday through saturday at 01:00 differential backup
            differential: "0 1 * * 1-6"
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 2Gi
      sidecars:
        pgbackrest:
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
        pgbackrestConfig:
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 200m
  users:
    - name: janus-idp
      options: "SUPERUSER"
