app:
  baseUrl: ${RHDH_BASE_URL}
  title: Red Hat Developer Hub
  branding:
    fullLogo: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/Pgo8IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDIwMDEwOTA0Ly9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSLzIwMDEvUkVDLVNWRy0yMDAxMDkwNC9EVEQvc3ZnMTAuZHRkIj4KPCEtLSBDcmVhdGVkIHVzaW5nIEtyaXRhOiBodHRwczovL2tyaXRhLm9yZyAtLT4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIAogICAgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiCiAgICB4bWxuczprcml0YT0iaHR0cDovL2tyaXRhLm9yZy9uYW1lc3BhY2VzL3N2Zy9rcml0YSIKICAgIHhtbG5zOnNvZGlwb2RpPSJodHRwOi8vc29kaXBvZGkuc291cmNlZm9yZ2UubmV0L0RURC9zb2RpcG9kaS0wLmR0ZCIKICAgIHdpZHRoPSIxNjBwdCIKICAgIGhlaWdodD0iODBwdCIKICAgIHZpZXdCb3g9IjAgMCAxNjAgODAiPgo8ZGVmcy8+Cjx0ZXh0IGlkPSJzaGFwZTAiIGtyaXRhOnVzZVJpY2hUZXh0PSJ0cnVlIiB0ZXh0LXJlbmRlcmluZz0iYXV0byIga3JpdGE6dGV4dFZlcnNpb249IjMiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0wLjE3NzMyMDYxNTAzNDE1NSwgNTQuMjYyNSkiIGZpbGw9IiNmZmZmZmYiIHN0cm9rZS1vcGFjaXR5PSIwIiBzdHJva2U9IiMwMDAwMDAiIHN0cm9rZS13aWR0aD0iMCIgc3Ryb2tlLWxpbmVjYXA9InNxdWFyZSIgc3Ryb2tlLWxpbmVqb2luPSJiZXZlbCIgbGV0dGVyLXNwYWNpbmc9IjAiIHdvcmQtc3BhY2luZz0iMCIgc3R5bGU9InRleHQtYWxpZ246IHN0YXJ0O3RleHQtYWxpZ24tbGFzdDogYXV0bztmb250LWZhbWlseTogUmVkIEhhdCBEaXNwbGF5O2ZvbnQtc2l6ZTogNDA7Zm9udC13ZWlnaHQ6IDcwMDsiPjx0c3BhbiB4PSIwIj5RRTwvdHNwYW4+PC90ZXh0Pjx0ZXh0IGlkPSJzaGFwZTEiIGtyaXRhOnVzZVJpY2hUZXh0PSJ0cnVlIiB0ZXh0LXJlbmRlcmluZz0iYXV0byIga3JpdGE6dGV4dFZlcnNpb249IjMiIHRyYW5zZm9ybT0idHJhbnNsYXRlKDU3LjU2NDgyMDYxNTAzNDIsIDM1LjcyOTY4NzUpIiBmaWxsPSIjZmZmZmZmIiBzdHJva2Utb3BhY2l0eT0iMCIgc3Ryb2tlPSIjMDAwMDAwIiBzdHJva2Utd2lkdGg9IjAiIHN0cm9rZS1saW5lY2FwPSJzcXVhcmUiIHN0cm9rZS1saW5lam9pbj0iYmV2ZWwiIGxldHRlci1zcGFjaW5nPSIwIiB3b3JkLXNwYWNpbmc9IjAiIHN0eWxlPSJ0ZXh0LWFsaWduOiBzdGFydDt0ZXh0LWFsaWduLWxhc3Q6IGF1dG87Zm9udC1mYW1pbHk6IFJlZCBIYXQgVGV4dDtmb250LXNpemU6IDE0O2ZvbnQtd2VpZ2h0OiA3MDA7Ij48dHNwYW4geD0iMCI+UmVkIEhhdDwvdHNwYW4+PHRzcGFuIHg9IjAiIGR5PSIxOC41MTU2MjUiPkRldmVsb3BlciBIdWI8L3RzcGFuPjwvdGV4dD4KPC9zdmc+Cg=="
    iconLogo: "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/Pgo8IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDIwMDEwOTA0Ly9FTiIgImh0dHA6Ly93d3cudzMub3JnL1RSLzIwMDEvUkVDLVNWRy0yMDAxMDkwNC9EVEQvc3ZnMTAuZHRkIj4KPCEtLSBDcmVhdGVkIHVzaW5nIEtyaXRhOiBodHRwczovL2tyaXRhLm9yZyAtLT4KPHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIAogICAgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiCiAgICB4bWxuczprcml0YT0iaHR0cDovL2tyaXRhLm9yZy9uYW1lc3BhY2VzL3N2Zy9rcml0YSIKICAgIHhtbG5zOnNvZGlwb2RpPSJodHRwOi8vc29kaXBvZGkuc291cmNlZm9yZ2UubmV0L0RURC9zb2RpcG9kaS0wLmR0ZCIKICAgIHdpZHRoPSI4MHB0IgogICAgaGVpZ2h0PSI4MHB0IgogICAgdmlld0JveD0iMCAwIDgwIDgwIj4KPGRlZnMvPgo8dGV4dCBpZD0ic2hhcGUwIiBrcml0YTp1c2VSaWNoVGV4dD0idHJ1ZSIgdGV4dC1yZW5kZXJpbmc9ImF1dG8iIGtyaXRhOnRleHRWZXJzaW9uPSIzIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxLjU5OTk5OTk5OTk5OTk5LCA2Mi44MTI1KSIgZmlsbD0iI2ZmZmZmZiIgc3Ryb2tlLW9wYWNpdHk9IjAiIHN0cm9rZT0iIzAwMDAwMCIgc3Ryb2tlLXdpZHRoPSIwIiBzdHJva2UtbGluZWNhcD0ic3F1YXJlIiBzdHJva2UtbGluZWpvaW49ImJldmVsIiBsZXR0ZXItc3BhY2luZz0iMCIgd29yZC1zcGFjaW5nPSIwIiBzdHlsZT0idGV4dC1hbGlnbjogc3RhcnQ7dGV4dC1hbGlnbi1sYXN0OiBhdXRvO2ZvbnQtZmFtaWx5OiBSZWQgSGF0IE1vbm87Zm9udC1zaXplOiA2NDtmb250LXdlaWdodDogNzAwOyI+PHRzcGFuIHg9IjAiPlFFPC90c3Bhbj48L3RleHQ+Cjwvc3ZnPgo="
    theme:
      light:
        primaryColor: "#2A61A7"
        headerColor1: "rgb(216, 98, 208)"
        headerColor2: "rgb(216, 164, 98)"
        navigationIndicatorColor: "rgb(98, 216, 105)"
      dark:
        primaryColor: '#DC6ED9'
        headerColor1: 'rgb(190, 122, 45)'
        headerColor2: 'rgb(45, 190, 50)'
        navigationIndicatorColor: 'rgb(45, 113, 190)'
backend:
  baseUrl: ${RHDH_BASE_URL}
  cors:
    origin: ${RHDH_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  reading:
    allow:
      - host: 'github.com'
      - host: ${DH_TARGET_URL}
  auth:
    keys:
      - secret: temp
  cache:
    store: redis
    connection: redis://${REDIS_USERNAME}:${REDIS_PASSWORD}@redis:6379
    useRedisSets: true
  listen:
    host: ${DH_TARGET_URL}
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
    upgrade-insecure-requests: false
  database:
    client: better-sqlite3
    connection: ':memory:'
integrations:
  # Plugin: GitHub
  github:
    - host: github.com
      apps:
        - appId: ${GITHUB_APP_APP_ID}
          clientId: ${GITHUB_APP_CLIENT_ID}
          clientSecret: ${GITHUB_APP_CLIENT_SECRET}
          webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
          webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
          privateKey: |
            ${GITHUB_APP_PRIVATE_KEY}
        - appId: ${GITHUB_APP_JANUS_TEST_APP_ID}
          clientId: ${GITHUB_APP_JANUS_TEST_CLIENT_ID}
          clientSecret: ${GITHUB_APP_JANUS_TEST_CLIENT_SECRET}
          webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
          webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
          privateKey: |
            ${GITHUB_APP_JANUS_TEST_PRIVATE_KEY}
  bitbucketServer:
    - host: bitbucket.com
      apiBaseUrl: temp
      username: temp
      password: temp
  gitlab:
    - host: gitlab.com
      token: ${GITLAB_TOKEN}
auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: development
  session:
    secret: superSecretSecret 
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    google:
      development:
        clientId: ${GOOGLE_CLIENT_ID}
        clientSecret: ${GOOGLE_CLIENT_SECRET}
    oidc:
      development:
        metadataUrl: ${KEYCLOAK_AUTH_BASE_URL}/auth/realms/${KEYCLOAK_AUTH_REALM}
        clientId: ${KEYCLOAK_AUTH_CLIENTID}
        clientSecret: ${KEYCLOAK_AUTH_CLIENT_SECRET}
        prompt: auto
        callbackUrl: ${RHDH_BASE_URL}/api/auth/oidc/handler/frame
signInPage: oidc
techRadar:
  url: "http://${DH_TARGET_URL}/tech-radar"
proxy:
  skipInvalidProxies: true
  # endpoints: {}
  endpoints:
    # Other Proxies
    '/acr/api':
      target: 'https://rhdhqetest.azurecr.io/acr/v1/'
      changeOrigin: true
      headers:
        # If you use Bearer Token for authorization, please replace the 'Basic' with 'Bearer' in the following line.
        Authorization: '${ACR_SECRET}'
      # Change to "false" in case of using self hosted artifactory instance with a self-signed certificate
      secure: false
    '/quay/api':
      target: https://quay.io/
      headers:
        X-Requested-With: 'XMLHttpRequest'
      changeOrigin: true
      secure: true
    '/add-test-header': 
      target: http://${RHDH_BASE_URL}:7007/api/simple-chat
      credentials: forward
      headers:
        'x-proxy-test-header': 'hello!'
catalog:
  import:
    entityFilename: catalog-info.yaml
    # pullRequestBranchName: rhdh-integration
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [API, Component, Group, Location, Resource, System, Template]
  locations:
    - type: url
      target: https://github.com/redhat-developer/rhdh/blob/main/catalog-entities/all.yaml
    - type: url
      target: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates.yaml
    - type: url
      target: https://github.com/backstage/community-plugins/blob/main/workspaces/scaffolder-backend-module-kubernetes/plugins/kubernetes-actions/examples/templates/01-kubernetes-template.yaml
    - type: url
      target: https://github.com/janus-qe/acr-catalog/blob/main/catalog-info.yaml
    - type: url
      target: https://github.com/janus-qe/rhdh-test/blob/main/user.yml
      rules:
        - allow: [User]
    - type: url
      target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
      rules:
        - allow: [User, Group]
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_AUTH_BASE_URL}/auth
        loginRealm: ${KEYCLOAK_AUTH_LOGIN_REALM}
        realm: ${KEYCLOAK_AUTH_REALM}
        clientId: ${KEYCLOAK_AUTH_CLIENTID}
        clientSecret: ${KEYCLOAK_AUTH_CLIENT_SECRET}
        schedule:
          frequency: { minutes: 1 }
          timeout: { minutes: 1 }
    github:
      providerId:
        organization: '${GITHUB_ORG}'
        schedule:
          frequency: { minutes: 30}
          timeout: { minutes: 30}
    githubOrg:
      id: production
      githubUrl: "${GITHUB_URL}"
      orgs: ["${GITHUB_ORG}", "${GITHUB_ORG_2}"]
    gitlab:
      my-test-provider:
        group: rhdhqetest
        host: gitlab.com
        schedule:
          frequency:
            minutes: 1
          initialDelay:
            seconds: 15
          timeout:
            minutes: 1
dynatrace:
  baseUrl: temp
argocd:
  appLocatorMethods:
    - type: 'config'
      instances:
        - name: argoInstance1
          url: temp
          token: temp
        - name: argoInstance2
          url: temp
          token: temp
permission:
  enabled: false