kind: ConfigMap
apiVersion: v1
metadata:
  name: rbac-policy
data:
  rbac-policy.csv: |
    p, role:default/guests, catalog.entity.create, create, allow
    p, role:default/team_a, catalog-entity, read, allow
    g, user:xyz/user, role:xyz/team_a
    g, group:janus-qe/rhdh-qe-2-team, role:default/test2-role

    p, role:xyz/team_a, catalog-entity, read, allow
    p, role:xyz/team_a, catalog.entity.create, create, allow
    p, role:xyz/team_a, catalog.location.create, create, allow
    p, role:xyz/team_a, catalog.location.read, read, allow

    g, user:default/rhdh-qe, role:default/qe_rbac_admin
    p, role:default/qe_rbac_admin, kubernetes.proxy, use, allow
    p, role:default/qe_rbac_admin, catalog.entity.create, create, allow
    p, role:default/qe_rbac_admin, catalog.location.create, create, allow
    p, role:default/qe_rbac_admin, catalog.location.read, read, allow

    p, role:default/bulk_import, bulk.import, use, allow
    p, role:default/bulk_import, catalog.location.create, create, allow
    p, role:default/bulk_import, catalog.entity.create, create, allow
    g, group:janus-qe/rhdh-qe-2-team, role:default/bulk_import
